// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_and_supabase_chat_app/test/features/auth/presentation/viewmodels/auth_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_and_supabase_chat_app/core/error/failures.dart' as _i5;
import 'package:flutter_and_supabase_chat_app/features/auth/domain/entities/user.dart'
    as _i6;
import 'package:flutter_and_supabase_chat_app/features/auth/domain/usecases/get_current_user.dart'
    as _i9;
import 'package:flutter_and_supabase_chat_app/features/auth/domain/usecases/sign_in.dart'
    as _i7;
import 'package:flutter_and_supabase_chat_app/features/auth/domain/usecases/sign_out.dart'
    as _i8;
import 'package:flutter_and_supabase_chat_app/features/auth/domain/usecases/sign_up.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignUp].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUp extends _i1.Mock implements _i3.SignUp {
  MockSignUp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> call({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #username: username,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);
}

/// A class which mocks [SignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignIn extends _i1.Mock implements _i7.SignIn {
  MockSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);
}

/// A class which mocks [SignOut].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOut extends _i1.Mock implements _i8.SignOut {
  MockSignOut() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [GetCurrentUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUser extends _i1.Mock implements _i9.GetCurrentUser {
  MockGetCurrentUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User?>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User?>>.value(
              _FakeEither_0<_i5.Failure, _i6.User?>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User?>>);
}
