// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_and_supabase_chat_app/test/features/chat/presentation/viewmodels/chat_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_and_supabase_chat_app/core/error/failures.dart' as _i9;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/entities/message.dart'
    as _i11;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/edit_message.dart'
    as _i14;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/get_messages.dart'
    as _i10;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/send_message.dart'
    as _i7;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/toggle_like.dart'
    as _i13;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/watch_messages.dart'
    as _i12;
import 'package:flutter_and_supabase_chat_app/features/profile/domain/entities/profile.dart'
    as _i15;
import 'package:flutter_and_supabase_chat_app/features/profile/domain/usecases/get_profile.dart'
    as _i4;
import 'package:flutter_and_supabase_chat_app/features/profile/domain/usecases/get_profiles.dart'
    as _i5;
import 'package:flutter_and_supabase_chat_app/features/profile/presentation/viewmodels/profile_state.dart'
    as _i6;
import 'package:flutter_and_supabase_chat_app/features/profile/presentation/viewmodels/profile_viewmodel.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:riverpod/src/internals.dart' as _i3;
import 'package:state_notifier/state_notifier.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderContainer_1 extends _i1.SmartFake
    implements _i3.ProviderContainer {
  _FakeProviderContainer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeepAliveLink_2 extends _i1.SmartFake implements _i3.KeepAliveLink {
  _FakeKeepAliveLink_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderSubscription_3<State1> extends _i1.SmartFake
    implements _i3.ProviderSubscription<State1> {
  _FakeProviderSubscription_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetProfile_4 extends _i1.SmartFake implements _i4.GetProfile {
  _FakeGetProfile_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetProfiles_5 extends _i1.SmartFake implements _i5.GetProfiles {
  _FakeGetProfiles_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileState_6 extends _i1.SmartFake implements _i6.ProfileState {
  _FakeProfileState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SendMessage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessage extends _i1.Mock implements _i7.SendMessage {
  MockSendMessage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, void>> call({
    required String? content,
    required String? profileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #content: content,
              #profileId: profileId,
            }),
            returnValue: _i8.Future<_i2.Either<_i9.Failure, void>>.value(
              _FakeEither_0<_i9.Failure, void>(
                this,
                Invocation.method(#call, [], {
                  #content: content,
                  #profileId: profileId,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Either<_i9.Failure, void>>);
}

/// A class which mocks [GetMessages].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMessages extends _i1.Mock implements _i10.GetMessages {
  MockGetMessages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i11.Message>>> call({
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#currentUserId: currentUserId}),
            returnValue:
                _i8.Future<_i2.Either<_i9.Failure, List<_i11.Message>>>.value(
                  _FakeEither_0<_i9.Failure, List<_i11.Message>>(
                    this,
                    Invocation.method(#call, [], {
                      #currentUserId: currentUserId,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i2.Either<_i9.Failure, List<_i11.Message>>>);
}

/// A class which mocks [WatchMessages].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchMessages extends _i1.Mock implements _i12.WatchMessages {
  MockWatchMessages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<List<_i11.Message>> call({required String? currentUserId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#currentUserId: currentUserId}),
            returnValue: _i8.Stream<List<_i11.Message>>.empty(),
          )
          as _i8.Stream<List<_i11.Message>>);
}

/// A class which mocks [ToggleLike].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleLike extends _i1.Mock implements _i13.ToggleLike {
  MockToggleLike() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, void>> call({
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i8.Future<_i2.Either<_i9.Failure, void>>.value(
              _FakeEither_0<_i9.Failure, void>(
                this,
                Invocation.method(#call, [], {
                  #messageId: messageId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Either<_i9.Failure, void>>);
}

/// A class which mocks [EditMessage].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditMessage extends _i1.Mock implements _i14.EditMessage {
  MockEditMessage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, void>> call({
    required String? messageId,
    required String? newContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #messageId: messageId,
              #newContent: newContent,
            }),
            returnValue: _i8.Future<_i2.Either<_i9.Failure, void>>.value(
              _FakeEither_0<_i9.Failure, void>(
                this,
                Invocation.method(#call, [], {
                  #messageId: messageId,
                  #newContent: newContent,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Either<_i9.Failure, void>>);
}

/// A class which mocks [GetProfiles].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfiles extends _i1.Mock implements _i5.GetProfiles {
  MockGetProfiles() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i15.Profile>>> call({
    required List<String>? profileIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#profileIds: profileIds}),
            returnValue:
                _i8.Future<_i2.Either<_i9.Failure, List<_i15.Profile>>>.value(
                  _FakeEither_0<_i9.Failure, List<_i15.Profile>>(
                    this,
                    Invocation.method(#call, [], {#profileIds: profileIds}),
                  ),
                ),
          )
          as _i8.Future<_i2.Either<_i9.Failure, List<_i15.Profile>>>);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i3.Ref<State> {
  MockRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ProviderContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeProviderContainer_1(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i3.ProviderContainer);

  @override
  T refresh<T>(_i3.Refreshable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [provider]),
            returnValue: _i16.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
          )
          as T);

  @override
  void invalidate(_i3.ProviderOrFamily? provider) => super.noSuchMethod(
    Invocation.method(#invalidate, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(State?, State)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateSelf() => super.noSuchMethod(
    Invocation.method(#invalidateSelf, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onAddListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onRemoveListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onResume, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onCancel, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onDispose, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>(_i3.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#read, [provider]),
            returnValue: _i16.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
          )
          as T);

  @override
  bool exists(_i3.ProviderBase<Object?>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [provider]),
            returnValue: false,
          )
          as bool);

  @override
  T watch<T>(_i3.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [provider]),
            returnValue: _i16.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
          )
          as T);

  @override
  _i3.KeepAliveLink keepAlive() =>
      (super.noSuchMethod(
            Invocation.method(#keepAlive, []),
            returnValue: _FakeKeepAliveLink_2(
              this,
              Invocation.method(#keepAlive, []),
            ),
          )
          as _i3.KeepAliveLink);

  @override
  _i3.ProviderSubscription<T> listen<T>(
    _i3.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [provider, listener],
              {#onError: onError, #fireImmediately: fireImmediately},
            ),
            returnValue: _FakeProviderSubscription_3<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
          )
          as _i3.ProviderSubscription<T>);
}

/// A class which mocks [ProfileViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileViewModel extends _i1.Mock implements _i17.ProfileViewModel {
  MockProfileViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetProfile get getProfile =>
      (super.noSuchMethod(
            Invocation.getter(#getProfile),
            returnValue: _FakeGetProfile_4(
              this,
              Invocation.getter(#getProfile),
            ),
          )
          as _i4.GetProfile);

  @override
  _i5.GetProfiles get getProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#getProfiles),
            returnValue: _FakeGetProfiles_5(
              this,
              Invocation.getter(#getProfiles),
            ),
          )
          as _i5.GetProfiles);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i8.Stream<_i6.ProfileState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.ProfileState>.empty(),
          )
          as _i8.Stream<_i6.ProfileState>);

  @override
  _i6.ProfileState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProfileState_6(this, Invocation.getter(#state)),
          )
          as _i6.ProfileState);

  @override
  _i6.ProfileState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeProfileState_6(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i6.ProfileState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i18.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i6.ProfileState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> loadProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#loadProfile, [profileId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadProfiles(List<String>? profileIds) =>
      (super.noSuchMethod(
            Invocation.method(#loadProfiles, [profileIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i15.Profile? getProfileById(String? profileId) =>
      (super.noSuchMethod(Invocation.method(#getProfileById, [profileId]))
          as _i15.Profile?);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i6.ProfileState? old, _i6.ProfileState? current) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i18.RemoveListener addListener(
    _i18.Listener<_i6.ProfileState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i18.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
