// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_and_supabase_chat_app/test/features/chat/presentation/viewmodels/chat_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_and_supabase_chat_app/core/error/failures.dart' as _i5;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/entities/message.dart'
    as _i7;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/get_messages.dart'
    as _i6;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/send_message.dart'
    as _i3;
import 'package:flutter_and_supabase_chat_app/features/chat/domain/usecases/watch_messages.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SendMessage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessage extends _i1.Mock implements _i3.SendMessage {
  MockSendMessage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call({
    required String? content,
    required String? profileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #content: content,
              #profileId: profileId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#call, [], {
                  #content: content,
                  #profileId: profileId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [GetMessages].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMessages extends _i1.Mock implements _i6.GetMessages {
  MockGetMessages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Message>>> call({
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#currentUserId: currentUserId}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.Message>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.Message>>(
                    this,
                    Invocation.method(#call, [], {
                      #currentUserId: currentUserId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Message>>>);
}

/// A class which mocks [WatchMessages].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchMessages extends _i1.Mock implements _i8.WatchMessages {
  MockWatchMessages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i7.Message>> call({required String? currentUserId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#currentUserId: currentUserId}),
            returnValue: _i4.Stream<List<_i7.Message>>.empty(),
          )
          as _i4.Stream<List<_i7.Message>>);
}
